### ISSUE TITLE
func.py中151行的lists.values()报错

### ISSUE THREAD

**Issue by janleemark** [kiwirafe/xiangshi#2]

**Comment by kiwirafe** [comment]
你是用`list`来计算的吗？

**Comment by janleemark** [comment]
是的，input1和input2，均取为“['文本内容']”这种格式，API说明中写的列表格式不是很理解

**Comment by kiwirafe** [comment]
说实话，`list`还没有完全支持，准备在下一个版本中更新。解决方法就是把它存为一个文件，在填入文件名就可以了。

**Comment by janleemark** [comment]
好的，感谢，也期待您的下一版本。

**Comment by kiwirafe** [comment]
相识3.0.1发布了，在这个版本里，列表已经支持了。
比如说：
```xs.cossim(["abc"], ["xyz"]) ```
然后结果就是0.0

你还可以增加IDF的运算，如下：
```xs.cossim(["abc", "wxy"], ["xyz", "bcd"])```

更新相识版本：
```pip install xiangshi --upgrade```

**Comment by janleemark** [comment]
很受用，会持续关注该模块

**Comment by kiwirafe** [comment]
万分感谢
